services:
  oj-frontend:
    build: ./OnlineJudgeFE
    container_name: oj-frontend
    ports:
      - "3000:3000"
    environment:
      - TARGET=http://oj-backend:8000
      - PORT=3000
      - VUE_APP_GOOGLE_CLIENT_ID=${VUE_APP_GOOGLE_CLIENT_ID}
      - VUE_APP_GOOGLE_CLIENT_SECRET=${VUE_APP_GOOGLE_CLIENT_SECRET}
      - VUE_APP_GOOGLE_REDIRECT_URI=${VUE_APP_GOOGLE_REDIRECT_URI:-http://localhost:3000/oauth/callback}
    depends_on:
      - oj-backend

  oj-redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  oj-postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
    ports:
      - "5432:5432"  

  oj-judge:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS

  oj-backend:
    build: ./OnlineJudge
    # image: registry.cn-hongkong.aliyuncs.com/oj-image/backend:1.6.1
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"

  my-spring:
    build: ./test-project-oj
    container_name: my-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://oj-postgres:5432/onlinejudge
      - SPRING_DATASOURCE_USERNAME=onlinejudge
      - SPRING_DATASOURCE_PASSWORD=onlinejudge
      - SPRING_REDIS_HOST=oj-redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - oj-postgres
      - oj-redis
    ports:
      - "8080:8080"