services:
  oj-redis:
    networks:
      - judge-network
    platform: linux/amd64
    image: redis:7.2-alpine
    restart: always
    volumes:
      - ./data/redis:/data

  oj-judge-1:
    networks:
      - judge-network
    platform: linux/amd64
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    env_file: .env
    cpuset: "15"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/oj-judge/log:/log
      - ./data/judge_server/oj-judge/run:/judger
    environment:
      SERVICE_URL: http://oj-judge:8080
      BACKEND_URL: http://oj-backend:8000/api/judge_server_heartbeat/
      TOKEN: ${JUDGE_SERVER_TOKEN}

  oj-judge-2:
    networks:
      - judge-network
    platform: linux/amd64
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    env_file: .env
    cpuset: "16"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/oj-judge-2/log:/log
      - ./data/judge_server/oj-judge-2/run:/judger
    environment:
      SERVICE_URL: http://oj-judge-2:8080
      BACKEND_URL: http://oj-backend:8000/api/judge_server_heartbeat/
      TOKEN: ${JUDGE_SERVER_TOKEN}

  oj-judge-3:
    networks:
      - judge-network
    platform: linux/amd64
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    env_file: .env
    cpuset: "17"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/oj-judge-3/log:/log
      - ./data/judge_server/oj-judge-3/run:/judger
    environment:
      SERVICE_URL: http://oj-judge-3:8080
      BACKEND_URL: http://oj-backend:8000/api/judge_server_heartbeat/
      TOKEN: ${JUDGE_SERVER_TOKEN}

  oj-judge-4:
    networks:
      - judge-network
    platform: linux/amd64
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    env_file: .env
    cpuset: "18"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/oj-judge-4/log:/log
      - ./data/judge_server/oj-judge-4/run:/judger
    environment:
      SERVICE_URL: http://oj-judge-4:8080
      BACKEND_URL: http://oj-backend:8000/api/judge_server_heartbeat/
      TOKEN: ${JUDGE_SERVER_TOKEN}

  oj-judge-5:
    networks:
      - judge-network
    platform: linux/amd64
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    env_file: .env
    cpuset: "19"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/oj-judge-5/log:/log
      - ./data/judge_server/oj-judge-5/run:/judger
    environment:
      SERVICE_URL: http://oj-judge-5:8080
      BACKEND_URL: http://oj-backend:8000/api/judge_server_heartbeat/
      TOKEN: ${JUDGE_SERVER_TOKEN}

  oj-backend:
    image: parkleewalab/oj-backend:latest
    networks:
      - judge-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    platform: linux/amd64
    restart: always
    depends_on:
      - oj-redis
      - oj-judge-1
      - oj-judge-2
      - oj-judge-3
      - oj-judge-4
      - oj-judge-5
    volumes:
      - ./data/backend:/data
      - ./data/backend/log:/data/log
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JUDGE_SERVER_TOKEN=${JUDGE_SERVER_TOKEN}
      - REDIS_HOST=oj-redis
      - REDIS_PORT=6379
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=http://judge.walab.info,https://judge.walab.info
      - USE_X_FORWARDED_HOST=true
    expose:
      - "8080"

  oj-micro-service:
    image: parkleewalab/oj-micro-service:latest
    networks:
      - judge-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    platform: linux/amd64
    restart: always
    environment:
      - SSO_INTROSPECT_URL=http://oj-backend:8000/api/sso
      - REDIS_URL=redis://oj-redis:6379
      - 'REDIS_SESSION_PREFIX=ms:session:'
      - TOKEN_COOKIE_NAME=ms_token
      - LOCAL_TOKEN_TTL_SECONDS=7200
      - TEST_CASE_DATA_PATH=/test_case
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - CODE_SAVE_TTL_SECONDS=5
      - 'REDIS_CODE_SAVE_PREFIX=ms:autosave'
    volumes:
      - ./data/backend/test_case:/test_case:rw
      - ./data/micro_service/log:/log
    depends_on:
      - oj-redis
      - oj-backend
    expose:
      - "8080"

networks:
  judge-network:
    external: true
    name: judge-network