services:
  oj-frontend:
    networks:
      - judge-network
    build:
      context: ./OnlineJudgeFE
      args:
        VUE_APP_GOOGLE_CLIENT_ID: ${VUE_APP_GOOGLE_CLIENT_ID}
        VUE_APP_GOOGLE_CLIENT_SECRET: ${VUE_APP_GOOGLE_CLIENT_SECRET}
        VUE_APP_GOOGLE_REDIRECT_URI: ${VUE_APP_GOOGLE_REDIRECT_URI}
    container_name: oj-frontend
    env_file: .env
    environment:
      - TARGET=http://oj-backend:8000
      - TARGET_HOST=${SERVICE_DOMAIN}
      - PORT=8080
      - VUE_APP_GOOGLE_CLIENT_ID=${VUE_APP_GOOGLE_CLIENT_ID}
      - VUE_APP_GOOGLE_CLIENT_SECRET=${VUE_APP_GOOGLE_CLIENT_SECRET}
      - VUE_APP_GOOGLE_REDIRECT_URI=${VUE_APP_GOOGLE_REDIRECT_URI}
    ports:
      - "8080:8080"
    depends_on:
      - oj-backend

  oj-redis:
    networks:
      - judge-network
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data
    command: >
      redis-server
      --notify-keyspace-events Ex 
      --databases 16

  oj-judge:
    networks:
      - judge-network
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/oj-judge/log:/log
      - ./data/judge_server/oj-judge/run:/judger
    environment:
      SERVICE_URL: http://oj-judge:8080
      BACKEND_URL: http://oj-backend:8000/api/judge_server_heartbeat/
      TOKEN: ${JUDGE_SERVER_TOKEN}

  oj-backend:
    networks:
      - judge-network
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./OnlineJudge
    restart: always
    depends_on:
      - oj-redis
      - oj-judge
    volumes:
      - ./data/backend:/data
      - ./data/backend/log:/data/log
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JUDGE_SERVER_TOKEN=${JUDGE_SERVER_TOKEN}
      - REDIS_HOST=oj-redis
      - REDIS_PORT=6379

  oj-micro-service: 
    networks:
      - judge-network
    build: ./micro-service-server 
    ports:
      - "9000:8000"
    environment:
      - SSO_INTROSPECT_URL=http://oj-backend:8000/api/sso
      - REDIS_URL=redis://oj-redis:6379
      - REDIS_SESSION_PREFIX="ms:session:"
      - TOKEN_COOKIE_NAME=ms_token
      - LOCAL_TOKEN_TTL_SECONDS=7200
      - TEST_CASE_DATA_PATH=/test_case 
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - CODE_SAVE_TTL_SECONDS=5
      - REDIS_CODE_SAVE_PREFIX=ms:autosave
    volumes:
      - ./data/backend/test_case:/test_case:rw 
      - ./data/micro_service/log:/log 
    depends_on:
      - oj-redis 
      - oj-frontend
      - oj-backend
      - oj-judge

networks:
  judge-network:
    name: judge-network
    driver: bridge
