name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build front page
        run: |
          cd ./hgu-oj-front
          echo "VITE_API_URL=${{ vars.VITE_API_URL }}" >> .env
          echo "VITE_MS_API_BASE=${{ vars.VITE_MS_API_BASE }}" >> .env
          echo "VITE_CODE_AUTO_SAVE_INTERVAL_SECONDS=${{ vars.VITE_CODE_AUTO_SAVE_INTERVAL_SECONDS }}" >> .env
          echo "VITE_CODE_AUTO_SAVE_CACHE_TTL_SECONDS=${{ vars.VITE_CODE_AUTO_SAVE_CACHE_TTL_SECONDS }}" >> .env
          npm ci
          npm install -D @types/node
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/oj-backend:latest ./OnlineJudge
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/oj-micro-service:latest ./micro-service-server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/oj-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/oj-micro-service:latest

      - name: Deploy frontend on server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./hgu-oj-front/dist/*"
          target: "~/www/judge"

      - name: Deploy backend on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/hgu-oj
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S docker compose pull
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S docker compose up -d
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S docker logout
